"""add assigned_to to claims

Revision ID: 6a91772b7d47
Revises: 8433bb62f0a2
Create Date: 2026-07-29 11:54:37.074862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a91772b7d47'
down_revision = '8433bb62f0a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_claims_assigned_to_users', 'users', ['assigned_to'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_constraint('fk_claims_assigned_to_users', type_='foreignkey')
        batch_op.drop_column('assigned_to')

    # ### end Alembic commands ###
