"""add ocr_text to documents

Revision ID: 8433bb62f0a2
Revises: 28bac9743e34
Create Date: 2026-07-23 22:45:41.245640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8433bb62f0a2'
down_revision = '28bac9743e34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ocr_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('ocr_text')

    # ### end Alembic commands ###
